# Generated by Django 5.0.4 on 2024-05-01 08:58

from django.db import migrations


def transfer_data_profile(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    oc_Profile = apps.get_model('oc_lettings_site', 'Profile')

    for oc_profile in oc_Profile.objects.all():
        Profile.objects.create(
            id=oc_profile.id,
            user=oc_profile.user,
            favorite_city=oc_profile.favorite_city
        )

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0002_alter_profile_user')
    ]

    operations = [
        migrations.RunPython(transfer_data_profile),
    ]
