# Generated by Django 5.0.4 on 2024-04-30 14:25

from django.db import migrations


def transfer_data(apps, schema_editor):
    Address = apps.get_model('lettings', 'Address')
    Letting = apps.get_model('lettings', 'Letting')
    oc_Address = apps.get_model('oc_lettings_site', 'Address')
    oc_Letting = apps.get_model('oc_lettings_site', 'Letting')

    for oc_address in oc_Address.objects.all():
        Address.objects.create(
            id=oc_address.id,
            number=oc_address.number,
            street=oc_address.street,
            city=oc_address.city,
            state=oc_address.state,
            zip_code=oc_address.zip_code,
            country_iso_code=oc_address.country_iso_code
        )

    for oc_letting in oc_Letting.objects.all():
        address = Address.objects.get(id=oc_letting.address.id)
        Letting.objects.create(
            id=oc_letting.id,
            title=oc_letting.title,
            address=address
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
