# Generated by Django 5.0.4 on 2024-05-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0002_auto_20240430_1625"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
    ]
