version: 2

# Configuration de la construction
build:
  os: ubuntu-20.04
  tools:
    python: "3.12"

# Installation des dépendances
python:
  install:
    - requirements: requirements.txt

# Configuration Sphinx
sphinx:
  configuration: doc/source/conf.py

# Configuration du format de sortie
formats:
  - htmlzip
