# Generated by Django 5.0.4 on 2024-05-01 11:05

from django.db import migrations


def delete_old_tables(apps, schema_editor):
    OldTableAddress = apps.get_model('oc_lettings_site', 'Address')
    OldTableAddress.objects.all().delete()

    OldTableLetting = apps.get_model('oc_lettings_site', 'Letting')
    OldTableLetting.objects.all().delete()

    OldTableProfile = apps.get_model('oc_lettings_site', 'Profile')
    OldTableProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RunPython(delete_old_tables),
    ]
