name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/oc_lettings:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/oc_lettings:${{ github.sha }}

  pull_and_run_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Pull and run Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/oc_lettings:${{ github.sha }}
        docker run -d -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/oc_lettings:${{ github.sha }}
