name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build, tag, and push Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/your-repo:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/your-repo:${{ github.sha }}
      - name: Pull and run Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/your-repo:${{ github.sha }}
          docker run -d -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/your-repo:${{ github.sha }}
