name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build, tag, push, pull and run Docker image
        run: |
          docker build . --file Dockerfile --tag $DOCKER_USERNAME/your-repo:${{ github.sha }}
          docker push $DOCKER_USERNAME/your-repo:${{ github.sha }}
          docker pull $DOCKER_USERNAME/your-repo:${{ github.sha }}
          docker run -d -p 8080:80 $DOCKER_USERNAME/your-repo:${{ github.sha }}
