name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_test_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Run tests
        uses: pytest-dev/pytest-action@v2
      - name: Run linter
        uses: pycqa/flake8-action@v2
      - name: Publish coverage
        run: echo "Publish coverage results here"

  containerize:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: $DOCKERHUB_USERNAME/repository_name:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKER_REGISTRY: https://index.docker.io/v1/
      - name: Pull Docker image
        uses: docker/pull-action@v2
        with:
          name: $DOCKERHUB_USERNAME/repository_name:${{ github.sha }}
      - name: Start Docker container
        uses: docker/start-service-action@v1
        with:
          image: $DOCKERHUB_USERNAME/repository_name:${{ github.sha }}
          ports: 8000:8000
