name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_test_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Run linter
        run: flake8
      - name: Publish coverage
        run: echo "Publish coverage results here"

  containerize:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker@v2
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/repository_name:${{ github.sha }} .
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_EMAIL }} --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/repository_name:${{ github.sha }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/repository_name:${{ github.sha }}
          docker run -d -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/repository_name:${{ github.sha }}
